# Generated by Django 4.2.5 on 2023-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_alter_application_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='pincode',
            new_name='pin',
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='phonenumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
