# Generated by Django 4.2.5 on 2023-10-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_rename_dob_application_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(),
        ),
    ]
