# Generated by Django 4.2.5 on 2023-10-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerformmodel',
            old_name='password2',
            new_name='confirm_password',
        ),
    ]
